/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
        "colors": {
            "on-tertiary-container": "#31057e",
            "primary-container": "#a078ff",
            "tertiary-fixed-dim": "#cebdff",
            "surface-bright": "#38393b",
            "inverse-on-surface": "#303033",
            "on-surface-variant": "#cbc3d7",
            "tertiary-fixed": "#e8ddff",
            "on-secondary-fixed": "#1a1c1f",
            "on-secondary": "#2f3034",
            "on-surface": "#e3e2e5",
            "on-primary-fixed-variant": "#5516be",
            "surface-container-highest": "#343537",
            "secondary": "#c6c6ca",
            "tertiary-container": "#9b7fed",
            "background": "#121315",
            "tertiary": "#cebdff",
            "error": "#ffb4ab",
            "on-secondary-container": "#b7b8bc",
            "primary": "#d0bcff",
            "inverse-primary": "#6d3bd7",
            "outline-variant": "#494454",
            "outline": "#958ea0",
            "on-primary-fixed": "#23005c",
            "surface": "#121315",
            "secondary-container": "#47494c",
            "error-container": "#93000a",
            "secondary-fixed-dim": "#c6c6ca",
            "on-tertiary-fixed-variant": "#4f319c",
            "on-primary": "#3c0091",
            "inverse-surface": "#e3e2e5",
            "on-tertiary-fixed": "#21005e",
            "on-secondary-fixed-variant": "#45474a",
            "on-error-container": "#ffdad6",
            "surface-tint": "#d0bcff",
            "on-tertiary": "#381385",
            "surface-container-high": "#292a2c",
            "surface-dim": "#121315",
            "secondary-fixed": "#e2e2e6",
            "surface-variant": "#343537",
            "primary-fixed": "#e9ddff",
            "on-primary-container": "#340080",
            "primary-fixed-dim": "#d0bcff",
            "on-error": "#690005",
            "on-background": "#e3e2e5",
            "surface-container-low": "#1b1c1e",
            "surface-container-lowest": "#0d0e10",
            "surface-container": "#1f2022"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "gutter": "24px",
            "unit": "4px",
            "container-max": "1200px",
            "margin-desktop": "32px",
            "margin-mobile": "16px"
        },
        "fontFamily": {
            "title-md": ["Inter"],
            "headline-xl": ["Inter"],
            "body-sm": ["Inter"],
            "body-md": ["Inter"],
            "label-caps": ["Inter"],
            "headline-lg": ["Inter"],
            "code": ["Inter"],
            "headline-lg-mobile": ["Inter"]
        },
        "fontSize": {
            "title-md": ["18px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500"}],
            "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
            "body-sm": ["13px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
            "body-md": ["14px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
            "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
            "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
            "code": ["13px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
            "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
        }
    },
  },
  plugins: [],
}
